apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: layershop.dangdang.com/cnlab/knative-helloworld:latest
          imagePullPolicy: IfNotPresent
